"""create manual_reviews table

Revision ID: 4e74b69940a8
Revises: 464f32dfc694
Create Date: 2026-09-27 12:54:45.970535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e74b69940a8'
down_revision: Union[str, Sequence[str], None] = '464f32dfc694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('verification_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verification_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_id', name='uq_manual_review_verification')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_reviews')
    # ### end Alembic commands ###
