"""create application_documents table

Revision ID: 7ac439b83a66
Revises: 3dccc0c30588
Create Date: 2026-09-27 12:09:59.118671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac439b83a66'
down_revision: Union[str, Sequence[str], None] = '3dccc0c30588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_documents',
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_documents')
    # ### end Alembic commands ###
